# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-02 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profileimage_status_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='status_main',
        ),
    ]
