# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 23:41
from __future__ import unicode_literals

import crowdfund.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funder_name', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FundItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to=crowdfund.models.scramble_uploaded_image)),
                ('name', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('estimate_min_price', models.IntegerField()),
                ('estimate_max_price', models.IntegerField()),
                ('hammer_price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='funder',
            name='funditem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funditems', to='crowdfund.FundItem'),
        ),
    ]
